### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
I added type definitions so people can use this module in TypeScript without any hassle.
I could submit them to [DefinitelyTyped](http://definitelytyped.org/) but there are some disadvantages, including (but not limited to):
- It being giant mono-repo
- Definition admission & maintenance is really slow
- Definitions can easily get out of sync*
- Requires another package install (which is completely unnecessary and inconvenient)

I hope you're willing to add these definitions, it'd make my life a lot easier 😄

* If you're concerned about maintenance I'll gladly maintain these definitions for you. Just mention me whenever you make a relevant change 😉

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
@HoldYourWaffle, one question I have though is

Does it matter in which directory to put `index.d.ts`? I see usually people put it just near the source file, in the same directory. You've decided to put it under `types`.

**Comment by HoldYourWaffle** [comment]
Not really, as long as the path in `package.json` is correct.
I also added a test for the definitions which requires some other files (like `tsconfig`), I figured putting these in a separate directory would cause the least clutter.

**Comment by nikitaeverywhere** [comment]
Good! Okay, now it's live as v1.0.2. Thank you for your effort in improving the package!

**Comment by HoldYourWaffle** [comment]
No problem, feel free to mention me if the definitions need to be updated :)

**Pull request merged**
